CREATE TABLE IF NOT EXISTS app_setting (
  setting_key   VARCHAR(100) PRIMARY KEY,
  setting_value VARCHAR(4000) NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_snapshot (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collected_at  VARCHAR(30) NOT NULL,
  period        VARCHAR(7)  NOT NULL,
  meters_ok     INT NOT NULL,
  meters_failed INT NOT NULL,
  errors        VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS usage_record (
  meter_key    VARCHAR(100) NOT NULL,
  period       VARCHAR(7)   NOT NULL,
  usage_value  DOUBLE PRECISION NOT NULL,
  collected_at VARCHAR(30)  NOT NULL,
  PRIMARY KEY (meter_key, period)
);

CREATE TABLE IF NOT EXISTS entitlement_status (
  meter_key    VARCHAR(100) PRIMARY KEY,
  name         VARCHAR(200) NOT NULL,
  usage_model  VARCHAR(20)  NOT NULL,
  usage_value  DOUBLE PRECISION NOT NULL,
  limit_value  DOUBLE PRECISION NOT NULL,
  unit         VARCHAR(30),
  pct_used     DOUBLE PRECISION,
  status       VARCHAR(20)  NOT NULL,
  sort_order   INT NOT NULL,
  computed_at  VARCHAR(30)  NOT NULL
);

CREATE TABLE IF NOT EXISTS alert_event (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule        VARCHAR(50)  NOT NULL,
  severity    VARCHAR(20)  NOT NULL,
  subject     VARCHAR(300) NOT NULL,
  message     VARCHAR(2000) NOT NULL,
  status      VARCHAR(20)  NOT NULL,
  source_ref  VARCHAR(200),
  notified    INT NOT NULL,
  created_at  VARCHAR(30)  NOT NULL,
  updated_at  VARCHAR(30)  NOT NULL,
  resolved_at VARCHAR(30)
);
CREATE INDEX IF NOT EXISTS ix_alert_status ON alert_event (status, rule);

CREATE TABLE IF NOT EXISTS job_run (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name    VARCHAR(50) NOT NULL,
  trigger_src VARCHAR(20) NOT NULL,
  status      VARCHAR(20) NOT NULL,
  started_at  VARCHAR(30) NOT NULL,
  finished_at VARCHAR(30) NOT NULL,
  message     VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS audit_poll_run (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_start_utc VARCHAR(30) NOT NULL,
  window_end_utc   VARCHAR(30) NOT NULL,
  status           VARCHAR(20) NOT NULL,
  events_fetched   INT NOT NULL,
  events_stored    INT NOT NULL,
  message          VARCHAR(4000),
  created_at       VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_event (
  event_id    VARCHAR(100) PRIMARY KEY,
  event_ts    VARCHAR(30)  NOT NULL,
  action      VARCHAR(100),
  subaction   VARCHAR(200),
  object_type VARCHAR(100),
  object_name VARCHAR(300),
  user_name   VARCHAR(200),
  org_id      VARCHAR(50),
  env_id      VARCHAR(50),
  risk        VARCHAR(20)  NOT NULL,
  raw_json    VARCHAR(8000)
);
CREATE INDEX IF NOT EXISTS ix_audit_ts ON audit_event (event_ts);

CREATE TABLE IF NOT EXISTS inventory_business_group (
  org_id       VARCHAR(50) PRIMARY KEY,
  name         VARCHAR(200) NOT NULL,
  parent_id    VARCHAR(50),
  collected_at VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_environment (
  env_id        VARCHAR(50) PRIMARY KEY,
  org_id        VARCHAR(50) NOT NULL,
  name          VARCHAR(200) NOT NULL,
  env_type      VARCHAR(30),
  is_production INT NOT NULL,
  collected_at  VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_application (
  app_id          VARCHAR(100) PRIMARY KEY,
  name            VARCHAR(200) NOT NULL,
  org_id          VARCHAR(50) NOT NULL,
  env_id          VARCHAR(50) NOT NULL,
  status          VARCHAR(50),
  runtime_version VARCHAR(50),
  collected_at    VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_api (
  api_id       VARCHAR(50) PRIMARY KEY,
  asset_id     VARCHAR(200),
  version      VARCHAR(50),
  label        VARCHAR(200),
  org_id       VARCHAR(50) NOT NULL,
  env_id       VARCHAR(50) NOT NULL,
  status       VARCHAR(50),
  collected_at VARCHAR(30) NOT NULL
);
